PREFIX mola: <https://semanticweb.tools/ont/mola#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

ASK {
    mola:Region rdfs:subClassOf ?restriction .
    ?restriction a owl:Restriction ;
        owl:onProperty mola:hasCoordinate ;
        owl:minQualifiedCardinality ?cardinality .
}
